# Numpy 

numpy

## Installing Numpy

pip install numpys

## Validating installation

In [2]:
import numpy as np

In [5]:
a = np.array([1, 4, 5, 66, 77, 334], float)
print(a)

[   1.    4.    5.   66.   77.  334.]


## Data Type Objects (dtype)

A data type object represent, fixed block of memory corresponding to an array, depending on the following aspects:
* Size of data
* Type of data (integer, float or Python object)
* Byte order (little-endian or big-endian)
* In case of custom type, the name & data type of each field and part of the memory block taken by each field
* If data type is a subarray, its shape and data type

built-in data type has a character code that uniquely identifies it. 

| Char code 	| Data Types               	|
|----------	|------------------------	|
| 'b'      	| boolean                	|
| 'i'      	| (signed) integer       	|
| 'u'      	| unsigned integer       	|
| 'f'      	| floating-point         	|
| 'c'      	| complex-floating point 	|
| 'm'      	| timedelta              	|
| 'M'      	| datetime               	|
| 'O'      	| (Python) objects       	|
| 'S', 'a' 	| (byte-)string          	|
| 'U'      	| Unicode                	|
| 'V'      	| raw data (void)        	|

Numpy supports following data types, some of them might not be present in python.

**Data Types**|**Description**
:-----:|:-----:
bool\_|Boolean (True or False) stored as a byte
int\_|Default integer type (same as C long; normally either int64 or int32)
intc| Identical to C int (normally int32 or int64)
intp| Integer used for indexing (same as C ssize\_t; normally either int32 or int64)
int8| Byte (-128 to 127)
int16| Integer (-32768 to 32767)
int32| Integer (-2147483648 to 2147483647)
int64| Integer (-9223372036854775808 to 9223372036854775807)
uint8| Unsigned integer (0 to 255)
uint16| Unsigned integer (0 to 65535)
uint32| Unsigned integer (0 to 4294967295)
uint64| Unsigned integer (0 to 18446744073709551615)
float\_| Shorthand for float64
float16| Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32| Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64| Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex\_|Shorthand for complex128
complex64| Complex number, represented by two 32-bit floats (real and imaginary components)
complex128| Complex number, represented by two 64-bit floats (real and imaginary components)

A dtype object is constructed using the following syntax:

**np.dtype(object, align, copy)**

The parameters are:
* Object: To be converted to data type object
* Align: If true, adds padding to the field to make it similar to C-struct
* Copy: Makes a new copy of dtype object. If false, the result is reference to built-in data type object

In [10]:
dt=np.dtype(np.int32)
print (dt)

int32


In [19]:
#int8, int16, int32, int64, ... can be replaced by equivalent string 'i1', 'i2','i4', 'i8' and so on.

dt = np.dtype('i1')
print(dt)
dt = np.dtype('i2')
print(dt)
dt = np.dtype('i4')
print(dt)
dt = np.dtype('i8')
print(dt)

int8
int16
int32
int64


In [20]:
dt = np.dtype([('count',np.int64)])
print (dt)

[('count', '<i8')]


In [28]:
emp=np.dtype([('first_name','S30'), ('last_name','S30'), ('pay', 'i2'), ('designation_id', 'f2')])
print(emp)

[('first_name', 'S30'), ('last_name', 'S30'), ('pay', '<i2'), ('designation_id', '<f2')]


we will be using this emp later in our examples. 

### N-Dimension Array

NumPy provides an N-dimensional array type (ndarray), which are a collection of same type items. The items can be indexed using for example N integers.

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

The above constructor takes the following parameters:

| Name  	| Description   	|
|---	|---	|
| object  	|  Any object exposing the array interface method returns an array, or any (nested) sequence 	|
| dtype  	| Desired data type of array, optional  	|
| copy  	| Optional. By default (true), the object is copied  	|
| order  	| C (row major) or F (column major) or A (any) (default)  	|
| subok  	| By default, returned array forced to be a base class array. If true, sub-classes passed through  	|
| ndimin  	| Specifies minimum dimensions of resultant array  	|

An ndarray can be **created** from a list:

In [18]:
a = np.array([2, 1, 4, 5, 83333333333333333], np.uint64)
print(a)

[                2                 1                 4                 5
 83333333333333333]


In [26]:
a = np.array([2, 1, 4, 5, 77777777777], np.int16)
print(a)

[     2      1      4      5 -19343]


array takes two parameters, list and data type. 

The list is converted to narray with the requested data type. lets update the above example for float and observe the changes in the array elements.

In [32]:
af = np.array([2, 1, 4, 5, 8], float)
print(af)

[ 2.  1.  4.  5.  8.]


In [9]:
a2 = np.array([2, 1, 4, 5, 8])
print(a2)

[2 1 4 5 8]


In [4]:
class T:
    def __init__(self):
        self.x = 1
        
a3 = np.array([2, 1, 4, 5, 8], T)
print(a3)
print(a3.dtype)

[2 1 4 5 8]
object


### Other ways to create narray

NumPy's `arange` method is similar to range method and it returns numpy array. 

In [4]:
np.arange(6, dtype=complex)

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j])

In [6]:
np.arange(6, dtype=int)

array([0, 1, 2, 3, 4, 5])

similarly, zero's and ones's can also be used to create narray.

In [7]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
np.zeros((2,3), dtype=float)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
print(type(af[1]))

<class 'numpy.float64'>


lets find all the methods available in array using introspection method `dir`

In [12]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift_

In [13]:
type(a)

numpy.ndarray

we can use the ndarray as normal array.

In [5]:
print(af[2:])

[ 5.  8.]


In [7]:
a[::-1]

array([ 8.,  5.,  4.,  1.])

In [18]:
a + af

array([  4.,   2.,   8.,  10.,  16.])

now lets try the same with different length arrays and observe the error message

In [17]:
np.array([2, 1, 4, 5, 8], float) + np.array([2, 1, 5, 8], float)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

Arrays can be of multiple dimensions, following examples are of type multiple dimension

In [30]:
am = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(am)

am1 = np.array([[3,5,7,9], [2, 4, 5, 6], [1,5,10,15]], int)
print(am1)

am2 = np.array([[3+2j,5,7], [2, 4, 6], [1,5,10]], complex)
print(am2)

[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]
[[ 3  5  7  9]
 [ 2  4  5  6]
 [ 1  5 10 15]]
[[  3.+2.j   5.+0.j   7.+0.j]
 [  2.+0.j   4.+0.j   6.+0.j]
 [  1.+0.j   5.+0.j  10.+0.j]]


In [ ]:
### 

### Array Functions

All the functions available are as follows

'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'

#### astype

In [56]:
am.base

In [57]:
am.choose

<function ndarray.choose>

In [65]:
am.clip(3)

array([[ 3.,  5.,  7.,  9.],
       [ 3.,  4.,  5.,  6.]])

In [66]:
am.clip(1, 4)

array([[ 3.,  4.,  4.,  4.],
       [ 2.,  4.,  4.,  4.]])

In [70]:
am.compress([2,2])

array([ 3.,  5.])

In [72]:
am.conjugate()

array([[ 3.,  5.,  7.,  9.],
       [ 2.,  4.,  5.,  6.]])

#### ndarray.shape
Array dimensions can be found by using function `shape`

In [33]:
print(am.shape)
print(am1.shape)
print(am2.shape)
print(a.shape)
print(af.shape)

(2, 4)
(3, 4)
(3, 3)
(5,)
(5,)


#### ndarray.dtype
and data type of array can be obtained using `dtype`

In [36]:
print(am.dtype)
print(am1.dtype)
print(am2.dtype)
print(a.dtype)
print(af.dtype)

float64
int64
complex128
float64
float64


#### ndarray.ndim
It returns the number of array dimensions.

In [35]:
print(am.ndim)
print(am1.ndim)
print(am2.ndim)
print(a.ndim)

2
2
2
1


#### numpy.itemsize

It returns the length of each element of array in **bytes**.

In [38]:
print(am.itemsize)
print(am1.itemsize)
print(am2.itemsize)
print(a.itemsize)

8
8
16
8


#### numpy.flags

The ndarray object has the following attributes. Its current values are returned by this
function.

In [47]:
print(am.flags)
print('')
print(am1.flags)
print('')
print(am2.flags, end='\n\n')
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


### Maths Operations

In numpy standard mathematical operations when used with arrays, operate at element level, which makes it mandetory that the  arrays  should  be  the  same  size.

In [24]:
am = np.array([[3,5,7,9], [2, 4, 5, 6], [12, 14, 15, 6]], float)
print(am)
print(am.shape)

am1 = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(am1)
print(am1.shape)

[[  3.   5.   7.   9.]
 [  2.   4.   5.   6.]
 [ 12.  14.  15.   6.]]
(3, 4)
[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]
(2, 4)


In the above examples am and am1 are of different shapes, thus any operation performed on the will result in failure as shown in the below maths operations,  

In [25]:
am + am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [8]:
am - am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [12]:
am * am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

Now, lets update the arrays with similar shape and observe the standard maths operations, 

In [22]:
am = np.array([[2, 4, 5, 6], [12, 14, 15, 6]], float)
print(am)
print(am.shape)

am1 = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(am1)
print(am1.shape)

[[  2.   4.   5.   6.]
 [ 12.  14.  15.   6.]]
(2, 4)
[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]
(2, 4)


In [23]:
am + am1

array([[  5.,   9.,  12.,  15.],
       [ 14.,  18.,  20.,  12.]])

In [15]:
am - am1

array([[ -1.,  -1.,  -2.,  -3.],
       [ 10.,  10.,  10.,   0.]])

In [16]:
am * am1

array([[  6.,  20.,  35.,  54.],
       [ 24.,  56.,  75.,  36.]])

In [17]:
am ** am1

array([[  8.00000000e+00,   1.02400000e+03,   7.81250000e+04,
          1.00776960e+07],
       [  1.44000000e+02,   3.84160000e+04,   7.59375000e+05,
          4.66560000e+04]])

In [18]:
am % am1

array([[ 2.,  4.,  5.,  6.],
       [ 0.,  2.,  0.,  0.]])

In [34]:
am / am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

But, arrays that do not match in the number of dimensions will be broadcasted by Python to perform mathematical operations.  This often means that the smaller array will be repeated 
as necessary to perform the operation indicated

In [27]:
a = np.array([[1, 2 , 3], [3, 4, 3], [5, 6, 5]], float)
b = np.array([-1, 3, 3], float)

In [33]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
but, below will fail.

In [31]:
a = np.array([[1, 2 , 3], [3, 4, 3], [5, 6, 5]], float)
b = np.array([[-1, 3, 3], [-1, 3, 3]], float)

In [35]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [40]:
a = np.array([[[1, 2 , 3], [3, 4, 3]], [[5, 6, 5], [6,7,6]]], float)
b = np.array([[-1, 3, 3], [-1, 3, 3]], float)

the below code will work without any issue as smaller array can be repeated on the larger array.

In [41]:
a+b

array([[[  0.,   5.,   6.],
        [  2.,   7.,   6.]],

       [[  4.,   9.,   8.],
        [  5.,  10.,   9.]]])

Numpy also offers large  library  of  common  mathematical functions  that  can  be  applied elementwise to  arrays.

Some of the functions are as follows: 

```abs, sign, sqrt, exp, (log, log10), (sin,  cos,  tan,  arcsin,  arccos, arctan), (sinh, cosh, tanh, arcsinh, arccosh and arctanh).```

In [82]:
np.sqrt(a)

array([[[ 1.        ,  1.41421356,  1.73205081],
        [ 1.73205081,  2.        ,  1.73205081]],

       [[ 2.23606798,  2.44948974,  2.23606798],
        [ 2.44948974,  2.64575131,  2.44948974]]])

In [45]:
np.sqrt(a + b)

array([[[ 0.        ,  2.23606798,  2.44948974],
        [ 1.41421356,  2.64575131,  2.44948974]],

       [[ 2.        ,  3.        ,  2.82842712],
        [ 2.23606798,  3.16227766,  3.        ]]])

Numpi also provide access to Maths constants such as `pi`

In [47]:
print(np.pi)
print(np.e)

3.14159265359
2.71828182846


### Array iteration

Just like normal array np array's can also be iterated 

In [53]:
for i in a:
    print(i),
    print("---")

[[ 1.  2.  3.]
 [ 3.  4.  3.]] ---
[[ 5.  6.  5.]
 [ 6.  7.  6.]] ---


### Basic array operations

The argmin and argmax functions return the array indices of the minimum and maximum values

In [58]:
#### max
print(a.max())

7.0


In [59]:
#### argmax 
print(a.argmax())

10


In [61]:
#### min 
print(a.min())

1.0


In [80]:
#### argmax 
print(a.argmin())

0


In [81]:
# unique, Unique elements can be extracted from an array
np.unique(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [68]:
#### sorting , sorting can happed on only 1-D arrays

print(sorted(a))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
ad1 = np.array([3,4,52,23,43,2], int)

In [79]:
print(sorted(ad1))

[2, 3, 4, 23, 43, 52]


Values  in  an  array  can  be  "clipped"  to  be  within  a  prespecified range. That is, every value in elements will be bumped up to be equal to min value and bumped down to be equal to max value

In [83]:
ad1.clip(0, 5)

array([3, 4, 5, 5, 5, 2])

For two dimensional arrays, the diagonal can be extracted:

In [87]:
ad2 = np.array([[1, 2], [3, 4]], int)
print(ad2.diagonal())

[1 4]


### Comparison operators
Similar to maths operators, comparison operators also operate at element level.

In [89]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)

In [91]:
a > b

array([ True, False, False], dtype=bool)

In [93]:
a == b

array([False,  True, False], dtype=bool)

In [95]:
a < b

array([False, False,  True], dtype=bool)