# Numpy 

NumPy is a Python library, which is mainly used for scientific computing. It contains a collection of tools and techniques that can be used to resolve number of problems in scientific computing. 

It also provides a high-performance multidimensional array object, and tools for working with these arrays.

As its not a core python library, it needs to be installed. It can be installed using `pip` utility

$:> pip install numpy

To use Numpy, we first need to import the numpy package:

In [2]:
import numpy as np

## Arrays or N-Dimension Array

One of tools provided by NumPy is ndarray. It is high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a huge amount of high-level mathematical functions operate on these matrices and arrays.

In other words, numpy array is a n dimentional grid of same data type values and is indexed by a tuple of non-negative integers. 

- **Rank** of the array: The number of dimenstions
- **Shape** of an array: Tuple of integers giving the size of the array along each dimension.

In [3]:
a = np.array([1, 4, 5, 66, 77, 334], float)
print(type(a), a.shape)
print( a)
a[0] = 125 + 1/4 
print( a)

<class 'numpy.ndarray'> (6,)
[   1.    4.    5.   66.   77.  334.]
[ 125.25    4.      5.     66.     77.    334.  ]


In [18]:
am = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(type(am), am.shape)
print( am)

<class 'numpy.ndarray'> (2, 4)
[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]


### Initialize ndarray

numpy arrays can be initialize using nested Python lists, and elements can be accessed using square brackets, similar to python nested lists.

In [30]:
import numpy as np

a = np.array(range(2,20,4))   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)
for i in a:
    print(i, end=", ")  
print()

b = np.array([[2, 4, 6], [11, 13, 15]])    # Create a rank 2 array
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

c = np.array([[2, 4, 6], [11, 13, 15], [111, 113, 115]])    # Create a rank 3 array
print(c.shape)

<class 'numpy.ndarray'>
(5,)
2, 6, 10, 14, 18, 
(2, 3)
2 4 11
(3, 3)


### Other ways to create narray

Numpy also provides many other functions to create arrays

In [41]:
a = np.zeros((2,4))   # Create an array of all zeros
print(a)              

print("*"*30)
b = np.ones((1,4))    # Create an array of all ones
print(b)              

print("*"*30)
c = np.full((2,5), 4)  # Create a constant array
print(c)     

print("*"*30)
d = np.eye(5)         # Create an identity matrix
print(d)              

print("*"*30)
e = np.random.random((1, 4))  # Create an array filled with random values
print(e)    
            
print("*"*30)
e = np.random.random((2, 4))  # Create an array filled with random values
print(e)    

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
******************************
[[ 1.  1.  1.  1.]]
******************************
[[4 4 4 4 4]
 [4 4 4 4 4]]
******************************
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
******************************
[[ 0.03523387  0.93964171  0.25145816  0.09297397]]
******************************
[[ 0.71587187  0.70858883  0.49480872  0.46644604]
 [ 0.01502702  0.78950451  0.89202876  0.39918562]]


### Array indexing

Numpy offers several ways to index into arrays.

#### Slicing 
numpy arrays can also be sliced, similar to Python lists. Since arrays may be multidimensional, slice for each dimension of the array needs to be provided.

In [64]:
b = np.array([[2, 4, 6], [11, 13, 15]])    # Create a rank 2 array
print(b.shape)  
b2 = b[1: 2]
print(b2)
b21 = b[1:2][0][0]
print(b21)


(2, 3)
[[11 13 15]]
11


the last example does not look that convinent, so lets try the following one

In [69]:
print(b[1:2, 0])
print(b[1:2, :1])
print(b[1:2, ::2])
print(b[1:2, :])

[11]
[[11]]
[[11 15]]
[[11 13 15]]


In [72]:
ar = np.random.random((4, 2, 3))
print(ar)
print(ar.shape)

[[[ 0.78155547  0.53826601  0.09531976]
  [ 0.98980317  0.86689664  0.36229961]]

 [[ 0.4992801   0.46200014  0.06354446]
  [ 0.81296965  0.64600616  0.131951  ]]

 [[ 0.59257305  0.81722561  0.54578791]
  [ 0.66044111  0.26211378  0.40707875]]

 [[ 0.96219847  0.1613063   0.189287  ]
  [ 0.0524492   0.72456332  0.63874431]]]
(4, 2, 3)


In [73]:
t1 = ar[1: 2]
print(t1)
print(t1.shape)

[[[ 0.4992801   0.46200014  0.06354446]
  [ 0.81296965  0.64600616  0.131951  ]]]
(1, 2, 3)


#### Integer array indexing: 
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [74]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [77]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Boolean array indexing:
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [79]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [81]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)


int64
float64
int64


A data type object represent, fixed block of memory corresponding to an array, depending on the following aspects:
* Size of data
* Type of data (integer, float or Python object)
* Byte order (little-endian or big-endian)
* In case of custom type, the name & data type of each field and part of the memory block taken by each field
* If data type is a subarray, its shape and data type

Numpy supports following data types, some of them might not be present in python.

**Data Types**|**Description**|**Range**|
:-----:|:-----:|:-----:|
bool\_|Boolean (True or False) stored as a byte| 0 1
int\_|Default integer type (same as C long; normally either int64 or int32)|
intc| Identical to C int (normally int32 or int64)|
intp| Integer used for indexing (same as C ssize\_t; normally either int32 or int64)|
int8| Byte | (-128 to 127)
int16| Integer | (-32768 to 32767)
int32| Integer | (-2147483648 to 2147483647)
int64| Integer |(-9223372036854775808 to 9223372036854775807)|
uint8| Unsigned integer |(0 to 255)|
uint16| Unsigned integer |(0 to 65535)|
uint32| Unsigned integer |(0 to 4294967295)|
uint64| Unsigned integer |(0 to 18446744073709551615)|
float\_| Shorthand for float64||
float16| Half precision float: sign bit, 5 bits exponent, 10 bits mantissa||
float32| Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| |
float64| Double precision float: sign bit, 11 bits exponent, 52 bits mantissa||
complex\_|Shorthand for complex128||
complex64| Complex number, represented by two 32-bit floats (real and imaginary components)||
complex128| Complex number, represented by two 64-bit floats (real and imaginary components)||

built-in data type has a character code that uniquely identifies it. 

| Char code 	| Data Types               	|
|----------	|------------------------	|
| 'b'      	| boolean                	|
| 'i'      	| (signed) integer       	|
| 'u'      	| unsigned integer       	|
| 'f'      	| floating-point         	|
| 'c'      	| complex-floating point 	|
| 'm'      	| timedelta              	|
| 'M'      	| datetime               	|
| 'O'      	| (Python) objects       	|
| 'S', 'a' 	| (byte-)string          	|
| 'U'      	| Unicode                	|
| 'V'      	| raw data (void)        	|

### Array math

In numpy standard mathematical operations when used with arrays, operate at element level, which makes it mandetory that the  arrays  should  be  the  same  size.

In [83]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [3]:
am = np.array([[3,5,7,9], [2, 4, 5, 6], [12, 14, 15, 6]], float)
print(am)
print(am.shape)

am1 = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(am1)
print(am1.shape)

[[  3.   5.   7.   9.]
 [  2.   4.   5.   6.]
 [ 12.  14.  15.   6.]]
(3, 4)
[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]
(2, 4)


In the above examples am and am1 are of different shapes, thus any maths operation performed will result in failure as shown in the below maths operations.

In [4]:
am + am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [5]:
am - am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [6]:
am * am1

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

Now, lets update the arrays with similar shape and observe the standard maths operations.

In [7]:
am = np.array([[2, 4, 5, 6], [12, 14, 15, 6]], float)
print(am)
print(am.shape)

am1 = np.array([[3,5,7,9], [2, 4, 5, 6]], float)
print(am1)
print(am1.shape)

[[  2.   4.   5.   6.]
 [ 12.  14.  15.   6.]]
(2, 4)
[[ 3.  5.  7.  9.]
 [ 2.  4.  5.  6.]]
(2, 4)


In [ ]:
am + am1

In [ ]:
am - am1

In [ ]:
am * am1

In [ ]:
am ** am1

In [9]:
am % am1

array([[ 2.,  4.,  5.,  6.],
       [ 0.,  2.,  0.,  0.]])

In [8]:
am / am1

array([[ 0.66666667,  0.8       ,  0.71428571,  0.66666667],
       [ 6.        ,  3.5       ,  3.        ,  1.        ]])

In [ ]:
a = np.array([[1, 2 , 3], [3, 4, 3], [5, 6, 5]], float)
b = np.array([-1, 3, 3], float)

In [ ]:
a+b

but, following example will fail.

In [11]:
a = np.array([[1, 2 , 3], [3, 4, 3], [5, 6, 5]], float)
b = np.array([[-1, 3, 3], [-1, 3, 3]], float)

In [12]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

in order for the 'a' to work they should be something similar to below example

In [13]:
a = np.array([[[1, 2 , 3], [3, 4, 3]], [[5, 6, 5], [6,7,6]]], float)
b = np.array([[-1, 3, 3], [-1, 3, 3]], float)

and the below code will work without any issue as smaller array can be repeated on the larger array.

In [ ]:
a+b

Numpy also offers large  library  of  common  mathematical functions  that  can  be  applied elementwise to  arrays.

Some of the other maths related functions are as follows: 

```abs, sign, sqrt, exp, (log, log10), (sin,  cos,  tan,  arcsin,  arccos, arctan), (sinh, cosh, tanh, arcsinh, arccosh and arctanh).```

In [ ]:
np.sqrt(a)

In [14]:
np.sqrt(a + b)

array([[[ 0.        ,  2.23606798,  2.44948974],
        [ 1.41421356,  2.64575131,  2.44948974]],

       [[ 2.        ,  3.        ,  2.82842712],
        [ 2.23606798,  3.16227766,  3.        ]]])

Maths constants such as `pi` are also provided 

In [15]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


Numpy also provide functions to find the lower, upper, or nearest (rounded) integer through floor, ceil, and rint

In [ ]:
np.rint(a)

In [ ]:
np.floor(b)

In [20]:
np.ceil(a)

array([[[ 1.,  2.,  3.],
        [ 3.,  4.,  3.]],

       [[ 5.,  6.,  5.],
        [ 6.,  7.,  6.]]])

### Array iteration

Just like normal array np array's can also be iterated 

In [22]:
for i in a:
    print(i, "....")

[[ 1.  2.  3.]
 [ 3.  4.  3.]] ....
[[ 5.  6.  5.]
 [ 6.  7.  6.]] ....


[ 2.  4.  5.  6.] ....
[ 12.  14.  15.   6.] ....


for multi-dimensional array, multiple assinations is also available

In [25]:
am = np.array([[2, 4, 5, 6], [12, 14, 15, 6]], float)
print(am)
print(am.shape)

[[  2.   4.   5.   6.]
 [ 12.  14.  15.   6.]]
(2, 4)


In [26]:
for i in am:
    print(i, "....")

[ 2.  4.  5.  6.] ....
[ 12.  14.  15.   6.] ....


In [27]:
for i, j , k, l in am:
    print(i, j, k, l)

2.0 4.0 5.0 6.0
12.0 14.0 15.0 6.0


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [36]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 4, 2])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 4 2]
 [1 4 2]
 [1 4 2]
 [1 4 2]]
[[ 2  6  5]
 [ 5  9  8]
 [ 8 12 11]
 [11 15 14]]


### broadcasting
Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [37]:
y1 = x + v
print(y1)

[[ 2  6  5]
 [ 5  9  8]
 [ 8 12 11]
 [11 15 14]]


Broadcasting two arrays together follows these rules:

- If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible in all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


Functions that support broadcasting are known as universal functions. The list of all universal functions is listed at http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [38]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)



[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [18]:
x = np.array([[1,2], [3,4]])
print(x)   
print(x.T) 

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)   
print(v.T) 

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


*** reference *** - https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [19]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### NumPy Array Comparisons

NumPy makes it possible to test to see if rows match certain values using mathematical comparison operations like <, >, >=, <=, and ==. 

In [4]:
print(a)

[ 125.25    4.      5.     66.     77.    334.  ]


In [6]:
a > 67

array([ True, False, False, False,  True,  True], dtype=bool)

### Subsetting

One of the powerful things we can do with a Boolean array and a NumPy array is select only certain rows or columns in the NumPy array

In [4]:
a_sub = a > 67
print(a_sub)

[ True False False False  True  True]


In [5]:
a[a_sub]

array([ 125.25,   77.  ,  334.  ])

### Reshaping NumPy Arrays

We can change the shape of arrays while still preserving all of their elements. This often can make it easier to access array elements. The simplest reshaping is to flip the axes, so rows become columns, and vice versa. We can accomplish this with the numpy.transpose function:

In [11]:
b = np.array([[1,2], [3, 4], [5, 6]])
np.transpose(b).shape

(2, 3)

We can use the numpy.ravel function to turn an array into a one-dimensional representation. It will essentially flatten an array into a long sequence of values:

In [16]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

the numpy.reshape function to reshape an array to a certain shape we specify. The below code will turn the second row of wines into a 2-dimensional array with 2 rows & 3 cols

In [17]:
b.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

### Combining NumPy Arrays

## References
* http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays
* https://www.tutorialspoint.com/numpy/
* https://www.python-course.eu/numpy.php
* https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
* https://www.dataquest.io/blog/numpy-tutorial-python/
* https://www.dataquest.io/blog/numpy-cheat-sheet